### ISSUE TITLE
[Android] Error fetching playlist on Android device

### ISSUE THREAD

**Issue by dragonator** [mps-youtube/pafy#100]
I'm trying to create an Android application to download my playlists.
I do it using python-for-android, kivy and buildozer.

The problem occurs when I try to get the playlist info:
`IOError:Error fetching playlist`

I tried to run the same script on my PC and it works (the same main.py).
Here is the link to my android branch:
https://github.com/dragonator/ytsync/tree/android

Do you have an idea how I can fix this? ...or anyone else :)

Thank you in advance!

Regards

**Comment by ids1024** [comment]
I don't know what is causing this. Try editing `pafy.py` to remove the first try/except in the `get_playlist()` function.

By that I mean to change this:

    try:
        allinfo = fetch_decode(url)  # unicode
        allinfo = json.loads(allinfo)

    except:
        raise IOError("Error fetching playlist %s" % m.groups(0))

To just this:

    allinfo = fetch_decode(url)  # unicode
    allinfo = json.loads(allinfo)

That should yield a more useful error message.

**Comment by dragonator** [comment]
I did what you proposed.
Then I got this:
`URLError:<urlopen error unknown url type:https>`

I googled about this and I found that this can be caused if Python wasn't compiled with SSL support.
I'm not sure if mine is, but since it is working on my PC I think it should be working as well on my phone.

....I'm starting to rage already and I'm one step behind reinstalling my Linux dist. :D

**Comment by ids1024** [comment]
> I googled about this and I found that this can be caused if Python wasn't compiled with SSL support.

Yes, that would appear to be the issue.

> I'm not sure if mine is, but since it is working on my PC I think it should be working as well on my phone.

Why? Your computer and phone are presumably running different python binaries, compiled for different architectures. The one on your computer is compiled with ssl support, while the one on your phone is not.
