### ISSUE TITLE
pafy uses regexes to parse youtube IDs

### ISSUE THREAD

**Issue by puckipedia** [mps-youtube/pafy#104]
This causes some interesting issues, as in (the completely valid URL) https://www.youtube.com/watch?av=3kRINw0tQtU&v=dQw4w9WgXcQ which shows up as 'Wolfgun - Burn' but actually opens the rickroll if you open it in a browser. This is a serious issue that could cause unwanted rickrolling :) (I use it in my IRC bot to handle youtube URL info, had to properly parse the url, was fun to find the issue)

**Comment by lol768** [comment]
I think the idea is that the constructor lets you pass in either a URL *or* a video ID. The way to handle this would be to parse the URL on your side (if you know you're only dealing with URLs) and then pass the id to the constructor.

I would worry that changing this behavior would be a breaking change for many.

**Comment by ids1024** [comment]
Well, it could be specifically modified to handle the last video id specified in the url, so it would behave the same way as the website.

**Comment by puckipedia** [comment]
how I would do it is to try to parse it as a video ID, then try the youtu.be thing, then use urlparse + urlparse_qs to parse it, so it would still support the normal features.

@ids1024: Close, but youtube uses the first video ID passed by query string (av= is not valid, so it ignores it). If you have two videos passed in the right way, it always uses the first (same behavior in Python, according to my tests)

**Comment by ids1024** [comment]
So, possible inputs:
- VIDEOID
- `http://youtu.be/VIDEOID` (or `http`, trailing `/`, use `urllib.parse.urlparse()` to handle this sanely)
- `http://youtube.com/watch?randomgarbage=martianinvasion&v=VIDEOID&othergarbage=test` (use `urllib.parse.urlparse()` to get the query string, then `urllib.parse.parse_qs()` to parse that, and get the `v` parameter)

Is there any possible (correct) input this does not handle? If not, I think this is probably better than the current regex.

**Comment by puckipedia** [comment]
I think the official docs say video ID or URL, so that should be fine I guess

**Comment by ids1024** [comment]
Yes, that is the intended functionality. My question is if any youtube urls would not function in this case.

There is also another regex used to parse playlist urls/ids, and I think it would make sense to replace that one as well.

**Comment by ids1024** [comment]
Implemented for videos (not yet playlists as well) in 103a2491180ffaf9019f078f2f2b12ac3b22db64.

Does this implementation seem reasonable?

**Comment by ids1024** [comment]
Implemented for playlist as well in 94f2bac271c75ebd9a7dc19a5c36c6dcc037d6a9.

**Comment by puckipedia** [comment]
Hey, the code seems to now allow `youtube.com.notactuallyyoutube.com` (I used `/^(www\.)?youtube\.[A-Za-z]{2,3}$/` to counter this), same with youtu.be. The rest is fine!

**Comment by ids1024** [comment]
@puckipedia Good point. Does it seem alright now: 02c78e41d8c54a4f24bd6bfcc6a2a04bc8f0d1cb?
