### ISSUE TITLE
Uses wrong extension for Opus codec

### ISSUE THREAD

**Issue by CreamyCookie** [mps-youtube/pafy#108]
According to [Wikipedia](https://en.wikipedia.org/wiki/Opus_%28audio_format%29) the official extension for Opus is `.opus`, but pafy currently uses `.ogg` for `audio.extension`, even though `audio.notes` is `'Opus'`.

**Comment by ids1024** [comment]
I am not entirely sure of the correct behavior. Ogg is a container format, and can contain opus audio or other formats. I decided to look at youtube-dl; it it seems all the formats pafy saves as ogg, youtube-dl saves as webm.

https://github.com/mps-youtube/pafy/blob/develop/pafy/pafy.py#L258-L259
https://github.com/mps-youtube/pafy/blob/develop/pafy/pafy.py#L269-L271

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L302-L309

**Comment by CreamyCookie** [comment]
@ids1024 Maybe I don't understand your point, but doesn't `audio.notes == 'Opus'` indicate that the extension should be `.opus`?

**Comment by ids1024** [comment]
Some video and audio formats are container formats, that can hold media in several codecs. Ogg and webm are both container formats, and both can hold opus data among other types.

**Comment by CreamyCookie** [comment]
@ids1024 Ah okay! So, Ogg Vorbis is the codec (`.ogg` files) and Ogg the container format.

I found something regarding Opus in a Ogg container. This is quote from https://en.wikipedia.org/wiki/Opus_%28audio_format%29#Features, which also has sources:

> Opus data can be encapsulated in Ogg containers. The content of such Ogg Opus streams should be specified as audio/ogg; codecs=opus and for Ogg Opus files the .opus filename extension is recommended.

**Comment by ids1024** [comment]
Oh, so `.opus` is the extension for opus data in an ogg container? In that case, I think you are correct. I have changed it.

**Comment by CreamyCookie** [comment]
@ids1024 Thanks. Should this bug stay open, or should I close it?

**Comment by ids1024** [comment]
The general rule currently followed by pafy and mps-youtube is to close bug reports when the fix is released, rather than just added to the develop branch. So, it can stay open for now.

**Comment by CreamyCookie** [comment]
@ids1024 Okay. btw. Will this change mean that `video.getbestaudio(preftype='ogg')` will return only Ogg Vorbis files and not Ogg Opus?

**Comment by ids1024** [comment]
Yes, since preftype matches against the file extension.
