### ISSUE TITLE
WARNING:root:Unknown itag: 13

### ISSUE THREAD

**Issue by jonathanpmartins** [mps-youtube/pafy#111]
video = pafy.new(url) gives me a warning.

    WARNING:root:Unknown itag: 13

 How can I get around this? The pafy version is "pafy-0.3.74-py2.py3-none-any.whl".

"python -W ignore script.py" dont resolve the problem.

My script:

```python```
import pafy
import sys
import warnings

def redirector(id):
    url = "https://www.youtube.com/watch?v=" + id
    video = pafy.new(url)
    best = video.getbest(preftype="mp4")
    return best.url

warnings.filterwarnings("ignore")

print redirector(sys.argv[1])

**Comment by ids1024** [comment]
Related: mps-youtube/mps-youtube#342

Adding this should suppress the warning:

    import logging
    logging.getLogger().setLevel(logging.ERROR)

This warning does not occur in git due to the changes in #109.

Oh, and the url part in the code is unneeded. `pafy.new()` takes either an id or an url.

**Comment by jonathanpmartins** [comment]
Thank you @ids1024!

So my problem was solved:

```python```
import pafy
import sys
import logging

def redirector(id):
    video = pafy.new(id)
    best = video.getbest(preftype="mp4")
    return best.url

logging.getLogger().setLevel(logging.ERROR)

print redirector(sys.argv[1])
