### ISSUE TITLE
Method to download stream in-memory

### ISSUE THREAD

**Issue by sevagh** [mps-youtube/pafy#113]
I am using pafy in a program to analyze the audio of YouTube videos. My solution now is to use Stream download() method to a TemporaryDirectory, since after analyzing audio I need to discard the file.

I thought of implementing a download_in_memory() method which creates a file in-memory (with BytesIO or SpooledTemporaryFile or something) for the case where we want to download without writing to disk. Do you think it's a good idea?

**Comment by ids1024** [comment]
This seems reasonable enough, but would it be better to have `download_to_stream()` or something to make it more generic? Or not; I don't know what would be the most useful or conventional.

**Comment by sevagh** [comment]
Actually my first patch called it "download_stream()", so I'm OK with "download_to_stream()". I'll get started on a patch.

**Comment by ids1024** [comment]
Oh, maybe this was unclear, but I meant that it could take a stream to write to as a parameter.

**Comment by sevagh** [comment]
It turns out ffmpeg decoding doesn't play well with file-like objects so I think ultimately this request is useless. Using a TemporaryDirectory is a fine solution.

I can always mount a TempDir in memory if I'm really worried about disk I/Os.

**Comment by ids1024** [comment]
> It turns out ffmpeg decoding doesn't play well with file-like objects

Can't ffmpeg take a media file from stdin?
