### ISSUE TITLE
Pafy with ironpython

### ISSUE THREAD

**Issue by barthr** [mps-youtube/pafy#121]
Is it possible to use pafy with IronPython?

Kind regards

**Comment by ids1024** [comment]
Maybe; have you tried it?

I'm not really familiar with ironpython. What is the advantage to using it?

**Comment by barthr** [comment]
No advantage imo but I just wanted to include it inside my c# wpf app

**Comment by ids1024** [comment]
I see. Maybe it would work, but it isn't really tested on anything but the standard cpython interpreter. You can try it, and if anything doesn't work, post here and maybe it can be fixed.

**Comment by championsyedm** [comment]
HERE ==> https://www.youtube.com/watch?v=VgTzKgX9Wqo
