### ISSUE TITLE
Pafy not work vevo!

### ISSUE THREAD

**Issue by xskylarx** [mps-youtube/pafy#124]
Send error while trying to download videos from vevo! for others the download without problems pafy python 3.4 V 0.4.2

Error https://www.youtube.com/watch?v=9Sc-ir2UwGU pafy not work

**Comment by grafixoner** [comment]
Update youtube-dl which Pafy uses to grab clips.  Youtube changes all the time, I'd suggest always try to update youtube-dl.

**Comment by xskylarx** [comment]
Thank you very much, and it works, great job !!! http://skytube.me/
