### ISSUE TITLE
Escape error in json

### ISSUE THREAD

**Issue by waissfowl** [mps-youtube/pafy#128]
Happened with pafy with playlist https://www.youtube.com/playlist?list=PLUzCj9_HB3LXQJJC2YhsQGYpzHrLwgX7o
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\pafy\pafy.py", line 1021, in get_playlist
    allinfo = json.loads(allinfo)
  File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python34\lib\json\decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 1 column 97696 (char 97695)```
pafy version 0.4.2

**Comment by waissfowl** [comment]
I forgot to precise that it happened while using the ```get_playlist() ``` function

**Comment by waissfowl** [comment]
It seems that it is [this video] (https://www.youtube.com/watch?v=ieUJBcJp2vE&list=PLUzCj9_HB3LXQJJC2YhsQGYpzHrLwgX7o&index=65)  which is causing trouble to the parser but when I download it alone (```pafy.new(url).getbest().download()```) it's working

**Comment by ids1024** [comment]
I think this is fixed by using the new `pafy.get_playlist2()` function in git.

**Comment by waissfowl** [comment]
Indeed it works. Thanks a lot !
