### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 556: ordinal not in range(128)

### ISSUE THREAD

**Issue by krishnawhite** [mps-youtube/pafy#129]
When I run the following code in Python 2.7.8:

```python
my_video = pafy.new('https://www.youtube.com/watch?v=JnWUe88M8b4') 
print(my_video)
```
I get the following error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 556: ordinal not in range(128)

Replacing line 125 in pafy/pafy.py:
```python
data = g.opener.open(url).read().decode()
```
with
```python
data = g.opener.open(url).read().decode('utf-8')
```
seems to fix the problem.

I would make a pull request, but I don't have the necessary permissions. Please can I be added?

**Comment by ids1024** [comment]
You don't need permission to create a pull request: https://help.github.com/articles/using-pull-requests/

**Comment by krishnawhite** [comment]
Yeah you're right. I was doing something stupid :s. Will create a PR today.
