### ISSUE TITLE
youtube video parse bug

### ISSUE THREAD

**Issue by wdfsinap** [mps-youtube/pafy#131]
hi, I use your source code v0.3.82. when I get the information with the video http://www.youtube.com/watch?v=gUYU3FqMLT8
it raises error:
IOError: Youtube says: <a href="http://www.youtube.com/watch?v=gUYU3FqMLT8&feature=player_embedded" target="_blank">Watch this video on YouTube.</a><br/>Playback on other websites has been disabled by the video owner. [gUYU3FqMLT8]

do you have any idea of how to fix this?

thanks

**Comment by ids1024** [comment]
Youtube-dl can't handle the video, so there is probably no (easy) way to fix this.
