### ISSUE TITLE
youtube-dl backend in windows

### ISSUE THREAD

**Issue by apournaras** [mps-youtube/pafy#137]
How can I add youtube-dl as a backend of pafy in windows? I tried to put youtube-dl.exe in the python install directory but the warning message keeps appearing when I import pafy

**Comment by ids1024** [comment]
Pafy uses youtube-dl as a module rather than calling the binary, so you need to install it with pip (or otherwise make it importable).

**Comment by apournaras** [comment]
That worked. Thanks for the help!
