### ISSUE TITLE
Error: from urlparse import parse_qs, unquote_plus

### ISSUE THREAD

**Issue by artemmus** [mps-youtube/pafy#139]
Can be fixed in file: pafy/backend_internal.py

by changing:

 19 else:
 20     from urllib2 import build_opener, HTTPError, URLError
 21     from urllib import unquote_plus
 22     from urlparse import parse_qs
 23     uni, pyver = unicode, 2

**Comment by ids1024** [comment]
I believe this was already fixed in git: #134.
