### ISSUE TITLE
KeyError: 'dashmpd'

### ISSUE THREAD

**Issue by artemmus** [mps-youtube/pafy#140]
In pafy/backend_internal.py

  File "pafy/backend_internal.py", line 434, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'

**Comment by Khang-NT** [comment]
same my error. full log:

> >>> video = pafy.new("kffacxfA7G4")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/khangneovip/pafy/pafy.py", line 126, in new
>     return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)
>   File "/home/khangneovip/pafy/backend_internal.py", line 47, in __init__
>     super(InternPafy, self).__init__(*args, **kwargs)
>   File "/home/khangneovip/pafy/backend_shared.py", line 95, in __init__
>     self._fetch_basic()
>   File "/home/khangneovip/pafy/backend_internal.py", line 94, in _fetch_basic
>     self.callback)
>   File "/home/khangneovip/pafy/backend_internal.py", line 433, in get_js_sm
>     dash_url = stream_info['dashmpd']
> KeyError: 'dashmpd'

Pafy work well with almost video, but some like Baby-Justin Bieber video had this error!

**Comment by ids1024** [comment]
This should be fixed by installing the optional but recommended `youtube-dl` dependency.

**Comment by ids1024** [comment]
I think I have the internal backend fixed in pafy's `develop` branch, though the youtube-dl backend is still recommended.

If anyone would like to test it, I would appreciate that.
