### ISSUE TITLE
Standalone import fails  (ValueError: Attempted relative import in non-package) pafy-0.5.0

### ISSUE THREAD

**Issue by kirankaranth1** [mps-youtube/pafy#143]
Downloaded pafy from https://github.com/np1/pafy/tarball/master

$ ls
backend_internal.py  backend_shared.py  backend_youtube_dl.py  g.py  __init__.py  jsinterp.py  pafy.py  pafy.pyc  playlist.py  util.py
$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pafy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pafy.py", line 39, in <module>
    from . import g
ValueError: Attempted relative import in non-package
>>>

**Comment by ids1024** [comment]
Do not run `import pafy` from inside the pafy subdirectory; run  it in the root of the repository.

**Comment by kirankaranth1** [comment]
Thanks Ian, it worked!
