### ISSUE TITLE
'Liked Videos' playlists cannot be downloaded

### ISSUE THREAD

**Issue by vbunardzhiev** [mps-youtube/pafy#149]
It is impossible to download a 'Liked Videos' playlist from YouTube since they start with 'LL' and the regex lets only RD/PL.

Simply adding 'LL' in the regex resolves the issue :)

`re.compile(r'((?:RD|PL|LL)[-_0-9a-zA-Z]+)$')`

**Comment by ids1024** [comment]
Thanks for pointing this out; fff9d585f919238786e038f396ae750cd4decb11 fixes this. If you (or anyone else) find any more prefixes youtube uses for playlists, please mention them.
