### ISSUE TITLE
How can I change the filename ?

### ISSUE THREAD

**Issue by ghost** [mps-youtube/pafy#153]
Before saving te file I want to append a number to his filename, it for example , 01_; In youtube_dl I saw that it is possible, can this be done also in paffy (using youtube_dl as dependency) ?

I check the documentation and didn't found anything, or maybe I just didn't look properly.

**Comment by ids1024** [comment]
The `.download()` method can take a path as it's first argument: http://pythonhosted.org/pafy/#Pafy.Stream.download

**Comment by PaulDevI** [comment]
Yes,  but it defines were the file is save. What I want to obtain is to change the filenames, not were are saved. Example:

_01_Video_Name_1
_02_Video_Name_2
_03_Video_Name_3

**Comment by ids1024** [comment]
If the path given to download is not an existing directory, it will be treated a a file name (similar to `cp`, `mv`, etc).

So use `stream.download('/path/to/destination/directory/filename.ext')`.

**Comment by manthanabc** [comment]
But it just leaves .part file
