### ISSUE TITLE
Getting Warning:youtube-dl not found

### ISSUE THREAD

**Issue by vishalgupta12** [mps-youtube/pafy#154]
Hi Friends,
  Recently I started using Pafy and it is working great.I am able to get,download any youtube videos.
 The only issue I am facing at the beginning is : 
"WARNING:root:pafy: youtube-dl not found; falling back to internal backend. This is not as well maintained as the youtube-dl backend. To hide this message, set the environmental variable PAFY_BACKEND to "internal"." 
After this warning everything working fine.
I tried to include youtube_dl as well but no luck.
Can anyone help me fix this warning issue.

Thanks.

**Comment by ids1024** [comment]
You need to install youtube-dl for the same python version as pafy.

So if you are using pafy in python 3, you need to install youtube-dl for python 3 (you can use `pip3 install youtube-dl`.

The internal backend was completely broken, and was just fixed a few days ago in the last pafy release, so you may be alright using it. The youtube-dl backend is still recommended though.

**Comment by Linux-joy** [comment]
Hallo,

my mps_youtube-Version is 0.2.7.1, my pafy-Version is 0.5.3.1.

I got the same error message above, but youtube-dl is still installed! It was manually downloaded and putted to /usr/local/bin.

Is there any possibility to get work pafy with this? The fallen back internal backend doesn't work, and additional installing youtube-dl for python 3 via pip3 might cause conflicts!

Thanks.

**Comment by ids1024** [comment]
@Linux-joy It's called as a library, so just manually placing it in /usr/local/bin.

Ideally, of course, it would be installed though the system's package manager. Arch packages a Python 3 version of youtube-dl, but Ubuntu/Debian is still on Python 2. I don't know about other distros.

**Comment by Linux-joy** [comment]
Hallo,

Thanks for your quick answer!!!

My solution is:

- Downloading youtube_dl manually from https://pypi.python.org/pypi/youtube_dl/ to "~/Programme/youtube_dl" in my personal home directory
- Unpacking it
- creating a symlink: `sudo ln -s ~/Programme/youtube_dl/youtube_dl /usr/local/lib/python3.4/dist-packages/youtube_dl`

Now mps-youtube works like a charm!

Bye
