### ISSUE TITLE
AttributeError: 'module' object has no attribute 'argv'

### ISSUE THREAD

**Issue by juanrubio** [mps-youtube/pafy#162]
Hi, I'm using 'pafy' in a C/C++ application and for that I'm embedding the Python interpreter using Boost.Python.

When I run the code, I get this crash:
```
Traceback (most recent call last):
  File "/home/joni/temp/lib/python2.7/site-packages/tizyoutubeproxy.py", line 26, in <module>
    import pafy
  File "/usr/local/lib/python2.7/dist-packages/pafy/__init__.py", line 20, in <module>
    if "test" not in sys.argv[0]:
AttributeError: 'module' object has no attribute 'argv'
```

The problem goes away if I add the following to `__init__.py`
```
if not hasattr(sys, 'argv'):
    sys.argv  = ['']
```

Not sure whether the problem is in Boost.Python or Pafy or perhaps I'm just doing something wrong.

**Comment by ids1024** [comment]
It's odd that Boost.Python doesn't implement sys.argv. Anyway, I think that code is somewhat unnecessary, so I removed it in 9f32ac7ccb43cba59b5469a7d1c294f92e170ae4.

**Comment by juanrubio** [comment]
Excellent!, thanks, that fixes my problem.
