### ISSUE TITLE
"token" parameter not in video info for unknown reason

### ISSUE THREAD

**Issue by richardbeattie** [mps-youtube/pafy#168]
When running this python code 

`video = pafy.new(url)`

with the url `https://www.youtube.com/watch?v=IdNtnzSeX5M` I get the error 

`IOError: ERROR: IdNtnzSeX5M: "token" parameter not in video info for unknown reason;`

When running just the youtube-dl command with the same url it can download it both as a video and as a audio file using the following commands respectivly
`youtube-dl https://www.youtube.com/watch?v=IdNtnzSeX5M`
`youtube-dl -f 140 https://www.youtube.com/watch?v=IdNtnzSeX5M`

As well when using a different url e.g. `https://www.youtube.com/watch?v=iD2rhdFRehU` it runs without errors

## Steps taken to resolve

- I have the most up to date version of both pafy and youtube-dl according to pip

- I have pafy setup to use my api key as according to https://github.com/mps-youtube/mps-youtube/issues/546

**Comment by ids1024** [comment]
Hm, `pafy.new` works with that video for me... if you have the latest youtube-dl version, I don't see what would cause this...

**Comment by richardbeattie** [comment]
Sorry for the late response,

I am still experiencing this issue, I have doubled check that I have both the latest version of pafy and youtube-dl and I have updated by python to its latest version(2.7.13).

I don't know will it help any further but here is the full error log

```
ERROR: IdNtnzSeX5M: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/local/lib/python2.7/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python2.7/site-packages/pafy/backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
IOError: ERROR: IdNtnzSeX5M: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by ids1024** [comment]
How do you have youtube-dl installed? Pafy calls youtube-dl as a library, so on certain configurations you could have both an up to date python 3 version and an outdated python 2 version.

You can check this with `import youtube_dl; print youtube_dl.version.__version__`

**Comment by richardbeattie** [comment]
I have youtube-dl installed through pip `pip install youtube-dl`, for as far as I am aware python 2.7.10

The output from
`import youtube_dl; print youtube_dl.version.__version__`

was` 2017.04.11` so it appears I am up to date

**Comment by o-jasper** [comment]
[In this other closed thread](https://github.com/ytdl-org/youtube-dl/issues/13045) people are saying they're having this issue only a few hours ago. (I seem to have the issue aswel)

**Comment by o-jasper** [comment]
Oh somehow i thought i was commenting to a youtube-dl issue. Anyway, it's fixed.. And the archlinux package is updated. It's magic!

**Comment by nngogol** [comment]
👁⛏️ I fix my problem by removing youtube-dl and installing it from http://yt-dl.org  ⛏️👁

```bash
# removing youtube-dl
sudo apt autoremove youtube-dl
# installing normal software
sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/bin/youtube-dl
chmod a+rx /usr/bin/youtube-dl
# Try to use youtube-dl AGAIN :)
```

watch video (60 sec): https://www.youtube.com/watch?v=sGUGFs1fpDE

**Comment by ritiek** [comment]
I'll close this since this seems to have been fixed in the newer youtube-dl releases.
