### ISSUE TITLE
Is it possible to retrieve a playlist with more than 300 videos?

### ISSUE THREAD

**Issue by yl1991** [mps-youtube/pafy#173]
Hi guys,

when I retrieved a playlist with 300 videos using `playlist = pafy.get_playlist(mobile_list)`, I found the length of `playlist['items']` is only 200, which means the command only retrieved 200 videos. 

Is it possible to retrieve more?
Many thanks in advance!

Best,
Yiming

**Comment by ids1024** [comment]
Use `get_playlist2()` instead.

**Comment by championsyedm** [comment]
hello :  https://www.youtube.com/watch?v=xXu9tjF0rcA
