### ISSUE TITLE
Human readable download progress

### ISSUE THREAD

**Issue by ritiek** [mps-youtube/pafy#175]
Hi, thanks a lot for building this library :smile:.

I was wondering when downloading a video or song, the download progress shows in `Bytes`. Is it possible to change it to other units like `KB's` and `MB's`?

**Comment by lollichop** [comment]
@ritiek Try editing ```backend_shared.py```, line numbers 591, 595 , 633. This could be an enhancement feature.

**Comment by ritiek** [comment]
@lollichop Your version works but it shows progress in whole numbers. For example, `0.0 MB` and then directly `1.0 MB` but nothing in between like `0.2 MB`, etc.

It would be nice if this is added as an optional parameter to the original pafy repo, something like `video.download(progress='KB')`. 😄 

Ping @ids1024.

**Comment by ritiek** [comment]
Implemented with #178.
