### ISSUE TITLE
Import fails 

### ISSUE THREAD

**Issue by MGF15** [mps-youtube/pafy#187]
i just grab pafy.py with wget and got this error ! 
```    import pafy
  File "pafy.py", line 39, in <module>
    from . import g
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by ids1024** [comment]
Hm, I don't think I've seen that. What python version do you have?

**Comment by MGF15** [comment]
python 3 4.3

**Comment by OriginalOmarion** [comment]
use pip and do: pip install pafy
then you can just do: import pafy
then i should work atleast it did for me

**Comment by MGF15** [comment]
https://github.com/mps-youtube/pafy#installation 
> Alternatively you can just grab the pafy.py file and import it in your python code 
it won't work 

@OriginalOmarion  i already install it by pip
