### ISSUE TITLE
Convert Audio Format .ogg to .mp3

### ISSUE THREAD

**Issue by githubgobi** [mps-youtube/pafy#192]
Is any possibility to store the files to different destination folder?
Is any possibility to convert .ogg format to .mp3 format on fly?

**Comment by silverbacknet** [comment]
What benefit would that have over installing and importing PyAV? What you propose involves integrating a massive library in order to duplicate effort. A more useful suggestion is having a callback that can be fed to `av` for however you wish to manipulate it.

**Comment by rachmadaniHaryono** [comment]
for anyone need it, here is example to convert it using pyav

```python
import os
import av
def convert2mp3(filename):
    inp = av.open(filename, 'r')
    ff, _ = os.path.splitext(filename)
    output_filename = ff + '.mp3'
    out = av.open(output_filename, 'w')
    ostream = out.add_stream("mp3")
    for frame in inp.decode(audio=0):
        frame.pts = None
        for p in ostream.encode(frame):
            out.mux(p)
    for p in ostream.encode(None):
        out.mux(p)
    out.close()
    return output_filename
```

example taken from here https://github.com/mikeboers/PyAV/issues/221

**Comment by githubgobi** [comment]
Thanks
