### ISSUE TITLE
Support indexing of pafy.Playlist object or conversation of the same into dict 

### ISSUE THREAD

**Issue by vn-ki** [mps-youtube/pafy#194]
```pafy.Playlist``` object is nice when you just have to iterate through the videos but it is very troublesome to work with in almost all other cases. This is mostly because it does not support indexing.

```pafy.mix``` returns a ```pafy.Playlist``` object and there is no visible way to convert it into the usual ```dict``` form.(The documentation is worth an update in this regard. It still says the return type is ```dict```). 

If there is some way to convert ```pafy.Playlist``` into ```dict``` or support indexing in the object, it would be very useful.

**Comment by ids1024** [comment]
Supporting indexing is probably a good idea. The `Playlist` class replaces the old dict format to deal with playlists longer than 200 items. To get that many items requires multiple requests, so it requests the next page of results only when you need it, to avoid unnecessary requests.

**Comment by vn-ki** [comment]
@ids1024 I have added this enhancement and created a PR #195. Can you please review it?
