### ISSUE TITLE
[Privacy issue] pafy uses HTTP by default (prefer_insecure = True)

### ISSUE THREAD

**Issue by cpupower** [mps-youtube/pafy#201]
For some reason, pafy seems to use the `prefer_insecure` option of  youtube-dl by default. This means that requests to youtube are done over HTTP instead of HTTPS, independently from the user-specified url. 

https://github.com/mps-youtube/pafy/blob/e6348cfc47c74857323cc9e781c61f3af507d1c9/pafy/g.py#L30

https://github.com/mps-youtube/pafy/blob/e6348cfc47c74857323cc9e781c61f3af507d1c9/pafy/backend_youtube_dl.py#L22-L29

HTTP requests (for example to `get_video_info`) will include the video id, which is sent unencrypted over the network, and as such visible to any attacker.

In my opinion `prefer_insecure = True` should never be the default setting, as this can be considered as a huge privacy issue, without the user even knowing, that traffic is unencrypted (i.e. visible to everyone).

Related to #115

In my opinion the user privacy should be prioritized over support for old mplayer versions, maybe instead a troubleshooting entry should be added, or otherwise a helpful hint should be given to the user. 

I think leaving users uninformed, silently transmitting requests in an unencrypted fashion is much worse, than software incompatible with old versions.

**Comment by ritiek** [comment]
Closed by the merge of #235.
