### ISSUE TITLE
.m4a files downloaded with pafy aren't supported by google play music, which supports .m4a files

### ISSUE THREAD

**Issue by imCalebM** [mps-youtube/pafy#205]
Google play music supports .m4a files, but when uploading a song downloaded using pafy it fails with the error 'unsupported file type'. I'm not sure what the reason could be, but I've tried uploading files downloaded with remux_audio=True and remux_audio=False with no success.

**Comment by vn-ki** [comment]
`remux_audio` requires `ffmpeg`. Do you have it installed?

**Comment by imCalebM** [comment]
Yeah, still no success

**Comment by imCalebM** [comment]
Apologies, I wasn't using the remux_audio parameter correctly.
