### ISSUE TITLE
Audio streams download speed issue

### ISSUE THREAD

**Issue by JoshukLite** [mps-youtube/pafy#206]
All audio streams of the video has slow download speed. On the average it starts after 25% already downloaded, then every 8th cycle of the `read` operation (in `BaseStream.download` method) takes up to 2.5 seconds (waiting for data, sleep?)
https://github.com/mps-youtube/pafy/blob/e6348cfc47c74857323cc9e781c61f3af507d1c9/pafy/backend_shared.py#L625-L635
Same result on all audio streams. No problems with video streams.
Here is a snippet of the method working time in milliseconds:
![capture](https://user-images.githubusercontent.com/17567540/37929794-9120cc54-3149-11e8-83eb-02d4f12596fe.PNG)

**Comment by vn-ki** [comment]
This will be fixed by #203. I will make the requested changes this weekend and get it merged.

**Comment by JoshukLite** [comment]
great! thanks

**Comment by ritiek** [comment]
Closed by #203.
