### ISSUE TITLE
ImportError: No module named pafy

### ISSUE THREAD

**Issue by jcconnell** [mps-youtube/pafy#207]
Trying to run the ytdl command line tool.

How to reproduce the problem on Ubuntu 17.10:
- python3 -m venv .
- source bin/activate
- pip install pafy
```
(env) $ ytdl
Traceback (most recent call last):
  File "~/auto_tube/bin/ytdl", line 22, in <module>
    import pafy
ImportError: No module named pafy
```

Expected result:
- Being able to run ytdl

Notes:
- If I launch a python interpreter, either with python or python3, I can import pafy without any issues.
- I experienced the same issue while testing on OSX

**Comment by vn-ki** [comment]
I would highly recommend you to use youtube-dl instead of ytdl. If you still want ytdl, read on.

The problem is probably that the shebang of ytdl reads `#!/usr/bin/python` and you are installing it with pip3. 
You can follow any of the following solutions:
- Change shebang to `#!/usr/bin/env python3` 
- Use `python3 path/to/ytdl` to start ytdl. (Find path using `whereis ytdl`)
- Install pafy using pip2.
- Make python refer to python3.

**Comment by jcconnell** [comment]
Thanks for those tips. The first one solved my problem. 

In case someone else lands on this page in their search, the second option reported this error:
``python3: can't open file 'ytdl': [Errno 2] No such file or directory``
I didn't try to third or fourth options.

I have looked at youtube-dl. My end goal is to automatically download the audio (no video, capped internet connection and trying to avoid wasting bandwidth) from a few YouTube channels as they are released. I know that youtube-dl is capable of solving this problem for video files, but according to their docs, it seems that audio must be extracted from the video files in post-processing. pafy on the other hand is capable of downloading the audio only. I know it's unrelated to this thread, but do you know if youtube-dl is capable of downloading audio only?

**Comment by vn-ki** [comment]
I have updated my comment to fix the second method. Close the issue if it is fixed.

Youtube-dl can extract audio only(refer their docs). But the module usage of youtube-dl is a bit cumbersome . pafy uses youtube-dl under the hood and makes the whole process easier. 

My point is youtube-dl is better when it comes to command line usage, but pafy shines as a module to download and get info about youtube videos.

**Comment by jcconnell** [comment]
Thanks for your help!

**Comment by srivathsanvenkateswaran** [comment]
I tried using pafy for downloading youtube video and I got the following error

`raise ImportError(
ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.`

**Comment by SpAnDaNpAtIl** [comment]
> I tried using pafy for downloading youtube video and I got the following error
> 
> `raise ImportError( ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.`

Hey srivathsanvenkateswaran, just pip install youtube-dl and your code will run fine

**Comment by srivathsanvenkateswaran** [comment]
> > I tried using pafy for downloading youtube video and I got the following error
> > `raise ImportError( ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.`
> 
> Hey srivathsanvenkateswaran, just pip install youtube-dl and your code will run fine

Thanks Mate! I tried and it worked!! :)

**Comment by obizayne** [comment]
> pip install youtube-dl

thanks
