### ISSUE TITLE
403 Error on few audiostream URLs when running Pafy on Django

### ISSUE THREAD

**Issue by sameerkumar18** [mps-youtube/pafy#209]
I use Pafy for getting M4A audiostreams, it works great on local server(Django). But when I deploy it(paid pythonanywhere), I often get 403 Errors on few audiostream URLs.

Here is how I am using Pafy at the moment -

```
import pafy
def converter_pafy(video_id):
    p = pafy.new(video_id)
    url = p.audiostreams[2].url

    return str(url) 
```

I tried few things, but still failed -

1) `del sys.module["pafy"]; del sys.module["youtube_dl"] `
2) `del p` (p is the pafy object)

Can someone please help me out? What am I doing wrong?

Thanks :)

**Comment by ritiek** [comment]
If you did install `youtube-dl` on the server and still get this error, the only reason I can think is YouTube just doesn't provide some of the videos to your deployed server (at pythonanywhere) (and `youtube-dl` can't find a workaround for it).

Also, can you share an example YouTube video that returns 403 on deployed server but not locally?

**Comment by sameerkumar18** [comment]
Yes, I am facing this problem even after having youtube-dl installed :/

This YouTube Video id has a problem - `BQ0mxQXmLsk` (works on the local server, but not on production)

**Comment by sameerkumar18** [comment]
UPDATE: I fixed this problem by changing my server location. The videos that I was trying to access were not made available by YouTube in the location of the server.
