### ISSUE TITLE
what if i dont like to use getbest()?

### ISSUE THREAD

**Issue by Succubussix** [mps-youtube/pafy#215]
what if i want to get lowest and midium posible? im using  it on stream . not downlaoding it.

**Comment by Succubussix** [comment]
i found it hahah sorry for bothering

**Comment by ritiek** [comment]
For anyone who stumbles on this in the future - The docs state how to use [stream lists attributes](https://pythonhosted.org/pafy/#stream-lists) on a Pafy object to access rest of the streams.
