### ISSUE TITLE
Sign in to confirm your age error

### ISSUE THREAD

**Issue by SoullessShadow** [mps-youtube/pafy#241]
Trying to get the song "Always Running" by Kevin Sherwood to work; using official one from Treyarch's youtube (link: https://www.youtube.com/watch?v=BwU7FR0uaaY) however, keep getting this error. Other songs work (haven't tried other age-restricted however will be updated when tested)

Python Version: 3.7.1
Pafy Version: 0.5.4
Youtube-dl Version: 2019.8.13
Using Windows 10 Pro Version 1903

EDIT: Tried Gummo by 6IX9Ine (link: https://www.youtube.com/watch?v=gAs9HZC9c7Y) and The Devil in I by Slipknot (link: https://www.youtube.com/watch?v=XEEasR7hVhA); same effect.

`ERROR: This video may be inappropriate for some users.
       Sign in to confirm your age
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "C:\Python37\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "C:\Python37\lib\site-packages\youtube_dl\extractor\youtube.py", line 2108, in _real_extract
    raise ExtractorError(error_message, expected=True)
youtube_dl.utils.ExtractorError: This video may be inappropriate for some users.
       Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pafy\backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "C:\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 819, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 624, in report_error
    self.trouble(error_message, tb)
  File "C:\Python37\lib\site-packages\youtube_dl\YoutubeDL.py", line 594, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: This video may be inappropriate for some users.
       Sign in to confirm your age

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jewel\OneDrive\Documents\Music\V1\Player.py", line 49, in <module>
    song(playlist)
  File "C:\Users\jewel\OneDrive\Documents\Music\V1\Player.py", line 13, in song
    video = pafy.new(url)
  File "C:\Python37\lib\site-packages\pafy\pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "C:\Python37\lib\site-packages\pafy\backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "C:\Python37\lib\site-packages\pafy\backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "C:\Python37\lib\site-packages\pafy\backend_youtube_dl.py", line 41, in _fetch_basic
    raise IOError(str(e).replace('YouTube said', 'Youtube says'))
OSError: ERROR: This video may be inappropriate for some users.
       Sign in to confirm your age`

**Comment by wigdanmalik** [comment]
any update because I have the same problem

**Comment by matih123** [comment]
same here. none of age restricted videos on youtube work. is they a way to work around it?

**Comment by KNO56** [comment]
Had the same issue, solved by installing the 'git' version of `pafy` (on Arch you can use an AUR helper such as `yay`; `yay -S python-pafy-git`).

**Comment by gnojus** [comment]
It's fixed in #235. (~~_mps-youtube_~~ _youtube-dl_ doesn't work with age restricted videos and `--prefer-insecure` flag)
However, new version of _pafy_ has not been released in a while #221
You can use the develop branch with
`pip3 install --user -U git+https://github.com/mps-youtube/pafy`
and it should work.
Or hope that _pafy_ will be updated anytime soon.
Though it doesn't look so.

**Comment by hrnr** [comment]
We should really release pafy. cc: @kraetzin, @ritiek

**Comment by ritiek** [comment]
@hrnr Yep! v0.5.5 was just released (#221). I'll close this as the new release no longer has this issue.

**Comment by AbhishekBhale** [comment]
It still has the sign-in issue.

**Comment by matih123** [comment]
> It still has the sign-in issue.

Wait, really?

**Comment by mongolsteppe** [comment]
Still present in version 2021.05.16

Sample video https://www.youtube.com/watch?v=pKWB-MVJ4sQ
![image](https://user-images.githubusercontent.com/75075420/119556141-4df4a980-bda7-11eb-87b1-d02ec35cb7a0.png)

**Comment by Magaret-TOTO** [comment]
I use the "Export Cookies" Add-on for firefox to save cookies txt.
Please note to SELECTE the "Prefix HttpOnly cookies" in Add-on.
And use `--cookies [path to cookies file]` command, it works.
Hope this helps.

**Comment by VVD** [comment]
> > It still has the sign-in issue.
> 
> Wait, really?

Yes.
youtube-dl --version
2021.06.06

**Comment by Oiubrab** [comment]
> > It still has the sign-in issue.
> 
> Wait, really?

I am seeing the problem as well. Same version as @VVD , getting:

`ERROR: Sign in to confirm your age`

Installing pafy does nothing to alleviate this error

**Comment by nise** [comment]
I am also experiencing this problem using the current version
