### ISSUE TITLE
youtube-dl ERROR: Unable to extract JS player URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### ISSUE THREAD

**Issue by ghost** [mps-youtube/pafy#278]
I get this error when importing certain videos.
How to solve this error?

**Comment by lemreaskin** [comment]
I have same problem. How can we solve it?

**Comment by ghost** [comment]
I found the answer! @4NTH3L1OS 
just type `pip install --upgrade youtube_dl` on cmd to solve the problem.

**Comment by lemreaskin** [comment]
Hmm it seems to have worked for now. Thanks @simsimler !
