### ISSUE TITLE
128kbps audio only :[

### ISSUE THREAD

**Issue by systems-rebooter** [mps-youtube/pafy#54]
Hey there, 

Thanks for the awesome lib! Somehow Pafy shows/downloads 128kbps audios only. 
I will use https://www.youtube.com/watch?v=F4MYdo7_shY as example below:

```
bash-3.2$  ytdl F4MYdo7_shY -t all 
Stream Type    Format Quality         Size            
------ ----    ------ -------         ----            
1      normal  mp4    [1280x720]      17 MB           
2      normal  webm   [640x360]        5 MB           
3      normal  mp4    [640x360]        6 MB           
4      normal  flv    [320x240]        4 MB           
5      normal  3gp    [320x240]        5 MB           
6      normal  3gp    [176x144]        1 MB           
7      video   m4v    [1920x1080]      7 MB           
8      video   webm   [1920x1080]      8 MB           
9      video   m4v    [1280x720]       5 MB           
10     video   webm   [720x480]        4 MB           
11     video   m4v    [854x480]        3 MB           
12     video   webm   [640x480]        2 MB           
13     video   m4v    [640x360]        1 MB           
14     video   webm   [480x360]        1 MB           
15     video   m4v    [426x240]        2 MB           
16     video   webm   [360x240]        1 MB           
17     video   m4v    [256x144]        1 MB           
18     audio   m4a    [128k]           3 MB           
19     audio   ogg    [128k]           3 MB           
bash-3.2$ 
```

```
>>> import pafy
>>> v = pafy.new("F4MYdo7_shY")
>>> v.audiostreams
[audio:m4a@128k, audio:ogg@128k]
>>> 
```

I used 3rd party tool to download 256kbps. 
Also, we got 192kbps sound stream while downloading 720p+ with Pafy

 Attaching related spectrograms:

![at the gala soundtrack - 256kbps](https://cloud.githubusercontent.com/assets/8888190/4388924/1d5d5b1a-43f0-11e4-8ac1-3f509823472b.png)

![at the gala soundtrack - 192kbps](https://cloud.githubusercontent.com/assets/8888190/4389210/1def5eea-43f3-11e4-9614-e3d23b7fef35.png)

![at the gala soundtrack - 128kbps](https://cloud.githubusercontent.com/assets/8888190/4388925/233501c8-43f0-11e4-902a-85014add0b27.png)

I am using latest stable version of Pafy:

```
Python 2.7.5
Pafy==0.3.62
```

Thanks again and keep up the good work!

**Comment by mazeen1998** [comment]
I cant see the any audio streams above 128k now. Is pafy still under active development. Is ffmpeg is to be installed on windows as .exe to be worked with ffmpeg-python pip editions.
