### ISSUE TITLE
Support Playlists Longer Than 200 Songs

### ISSUE THREAD

**Issue by ids1024** [mps-youtube/pafy#71]
This was reported as an issue in mpsyt (np1/mps-youtube#192) but it is a problem with pafy.

Youtube will return a maximum of 200 songs.  The solution to this is to send an additional request requesting another max 200 songs.

I can't seem to find any documentation on http://www.youtube.com/list_ajax, but I am guessing that it is version 1 of Youtube's API.  It seems like it would be better to use http://gdata.youtube.com/feeds/api/playlists/%s?v=2.  I have tried to change this, but it seems it will require modifications to several parts of the code, including the Pafy class.

The advantage of using this api is that it provides a good way to get additional songs.  Something like this will get the url for the next list of videos:

    url = next((i for i in t.finditer(t1 + 'link')
                     if i.get('rel') == 'next'), None).get('href')

I will see if I can find a way to get this to work with the list_ajax api.

**Comment by np1** [comment]
YouTube playlists used to have a maximum size of 200 items but it seems this restriction was dropped. I didn't implement the playlist retrieval part of pafy and also can't find any documentation on `list_ajax`

**Comment by ids1024** [comment]
If 200 used to be the limit, the old api probably doesn't support getting more.  I am guessing that `list_ajax` is the api from before Google acquired youtube.  I will work on changing it to use the new api.

**Comment by np1** [comment]
I am reluctant to include any changes that use gdata v2 because it will be turned off in the coming months.


Using v3 of the api requires obtaining a key for most request types - and obtaining a key requires agreeing to not access YouTube in the way that pafy does.

Some things specifically prohibited;

    - access any portion of any YouTube audiovisual content by any means other than use of a YouTube player or other video player expressly authorized by YouTube;
    - store copies of YouTube audiovisual content;




https://developers.google.com/youtube/2.0/developers_guide_protocol_deprecated
https://developers.google.com/youtube/youtube-api-list
https://developers.google.com/youtube/terms

**Comment by usebosespeakers** [comment]
I tried to use dump on a playlist size of 295 and it didn't even dump 200 items; I only got back 196.
v0.2.3

**Comment by ids1024** [comment]
@usebosespeakers That is because it could not retrieve 4 of the videos, probably because they have been deleted since the playlist was created.   If you want to get as many of the 295 videos as possible, you can use the branch from PR #72.

**Comment by usebosespeakers** [comment]
Thanks, I did see some deleted videos in the playlist. Glad to see it's automatically removing deleted items. This is helpful. Will check out [#72](https://github.com/np1/pafy/pull/72).
