### ISSUE TITLE
Wrong download with *.m4a files

### ISSUE THREAD

**Issue by xmollv** [mps-youtube/pafy#94]
So, i was just testing this to download the audio from a given URL:
```
import pafy
url = raw_input("Paste the YouTube URL:")
video = pafy.new(url)
best = video.getbestaudio().download(quiet=False)
```
It works. It downloads the audio, but the length of the file is exactly the double of the original one. So i have the first half working but the second part is completely silence. Am i doing something wrong or it's just broken?

I've tested it downloading *.ogg and they work fine, so it must be something with the *.m4a files. If you need it, i was trying to download this audio: https://www.youtube.com/watch?v=ThxaAo1QFSw

OSX 10.10.3
Python 2.7.6

**Comment by xmollv** [comment]
Nobody? I've upgraded to the latest version and it's still broken.

**Comment by lol768** [comment]
Hmm, this is interesting. 

Trying with Python2.7, can't reproduce:
```
➜  /tmp  python2.7 -V
Python 2.7.6
➜  /tmp  python2.7 x.py                                
Paste the YouTube URL:https://www.youtube.com/watch?v=ThxaAo1QFSw
➜  /tmp  mpv Mura\ Masa\ -\ Firefly\ \(feat.\ Nao\).m4a 
mpv: Symbol \`av_pix_fmt_descriptors' has different size in shared object, consider re-linking
Playing: Mura Masa - Firefly (feat. Nao).m4a
Detected file format: QuickTime / MOV (libavformat)
Clip info:
 major_brand: dash
 minor_version: 0
 compatible_brands: iso6mp41
 creation_time: 2015-05-24 04:06:00
 language: und
 handler_name: SoundHandler
[stream] Audio (+) --aid=1 --alang=und (aac)
Video: no video
Selected audio codec: AAC (Advanced Audio Coding) [lavc:aac]
AO: [pulse] 44100Hz stereo 2ch float
A: 00:00:31 / 00:03:48 (13%)
```

Modifying script for use with Python3 and removing old audio file, can't reproduce:
```
➜  /tmp  cat x.py 
import pafy
url = input("Paste the YouTube URL:")
video = pafy.new(url)
best = video.getbestaudio().download(quiet=False)
➜  /tmp  python3 x.py 
Paste the YouTube URL:https://www.youtube.com/watch?v=ThxaAo1QFSw
➜  /tmp  mpv Mura\ Masa\ -\ Firefly\ \(feat.\ Nao\).m4a 
mpv: Symbol \`av_pix_fmt_descriptors' has different size in shared object, consider re-linking
Playing: Mura Masa - Firefly (feat. Nao).m4a
Detected file format: QuickTime / MOV (libavformat)
Clip info:
 major_brand: dash
 minor_version: 0
 compatible_brands: iso6mp41
 creation_time: 2015-05-24 04:06:00
 language: und
 handler_name: SoundHandler
[stream] Audio (+) --aid=1 --alang=und (aac)
Video: no video
Selected audio codec: AAC (Advanced Audio Coding) [lavc:aac]
AO: [pulse] 44100Hz stereo 2ch float
A: 00:00:05 / 00:03:48 (2%)
```

Also plays correctly with `mplayer` and `vlc` for me. Pip info:

```
➜  /tmp  sudo pip show pafy
---
Name: pafy
Version: 0.3.74
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
➜  /tmp  sudo pip3 show pafy
---
Name: pafy
Version: 0.3.74
Location: /usr/local/lib/python3.4/dist-packages/pafy-0.3.74-py3.4.egg
Requires: 
➜  /tmp  
```

mpv version info:

```
mpv 0.3.4 (C) 2000-2013 mpv/MPlayer/mplayer2 projects
 built on 2014-02-01T17:09:32
libav library versions:
   libavutil       52.3.0 (runtime 52.18.100)
   libavcodec      54.35.0 (runtime 54.92.100)
   libavformat     54.20.3 (runtime 54.63.104)
   libswscale      2.1.1 (runtime 2.2.100)
   libavfilter     3.3.0 (runtime 3.42.103)
   libavresample   1.0.1 (runtime 1.1.0)
```

File info:

```
➜  /tmp  md5sum Mura\ Masa\ -\ Firefly\ \(feat.\ Nao\).m4a
66f5ec7a760a3af794fb3e8e855061b8  Mura Masa - Firefly (feat. Nao).m4a
➜  /tmp
```

How exactly are you playing the file? Is the same file being downloaded as I'm seeing above?

**Comment by xmollv** [comment]
The file is the same: md5 → 66f5ec7a760a3af794fb3e8e855061b8

As you can see in the image attached, the length is wrong. The second half of the song is pure silence. 
![captura de pantalla 2015-07-25 a las 18 59 43](https://cloud.githubusercontent.com/assets/8229382/8890398/84cda7d8-32ff-11e5-91c6-00d9521c0b25.png)

**Comment by ids1024** [comment]
I was able to reproduce this by playing the song in vlc rather than mpv. I don't know the cause.

**Comment by lol768** [comment]
How odd. Which version of VLC were you using, @ids1024?

"2.1.6 Rincewind" seems to cope with it okay for me:

![](https://i.imgur.com/SmmyQbE.png)

**Comment by ids1024** [comment]
I have vlc 2.2.1.

My guess would be that the length in the metadata is incorrect, but mpv (and older versions of vlc?) just ignores that and calculates the length itself. As for why, I don't know.

**Comment by lol768** [comment]
> My guess would be that the length in the metadata is incorrect, but mpv (and older versions of vlc?) just ignores that and calculates the length itself. As for why, I don't know.

I think you're right there, I can reproduce if I update vlc to 2.2.1.

**Comment by ids1024** [comment]
`youtube-dl -f bestaudio ThxaAo1QFSw` seems to download the correct file.

Perhaps pafy should pull in youtube-dl as a dependency, and use it instead of duplicating the effort? Pafy can then just have code for youtube metadata and simple wrappers for calling youtube-dl functions. That should solve some of the problems pafy currently has.

@np1 What do you think about making pafy depend on youtube-dl?

**Comment by lol768** [comment]
I'm assuming it's this commit here which makes the files downloaded with youtube-dl work correctly: https://github.com/rg3/youtube-dl/commit/62cd676c7474f696804eda653558ada94c5953a0

One of the linked issues states:

> The problem is that youtube's MP4 container has an empty "time-to-sample atom" (a.k.a. seek table).

Indeed, if you take the file downloaded by pafy and run `ffmpeg -i Mura\ Masa\ -\ Firefly\ \(feat.\ Nao\).m4a -c copy -f mp4 test1.m4a` on it, the problem is fixed.

**Comment by ids1024** [comment]
@lol768 Good job finding that. It looks like pafy already has this functionality, just pass `remux_audio=True` to `download()` (is that meant for this issue, or something else?). It calls ffmpeg/avconv, specifically `ffmpeg -y -i INFILE -acodec copy -vn OUTFILE`.

I still think it would be better to just depend on youtube-dl, and let them deal with all the quirks. That would fix other issues, and reduce the maintenance needed by pafy.

**Comment by ids1024** [comment]
See PR #109 for bringing in youtube-dl as a dependency. Currently it does not affect this issue, since the downloading code is the same (except getting the url from youtube-dl).
